stages:
- name: get-latest-binary
  steps:
  - runScriptConfig:
      image: alpine
      shellScript: |+
        echo "I will get the latest binary version!"

- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: satomic/2048
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
