kind: Service
apiVersion: v1
metadata:
  name: 2048
  namespace: default
spec:
  selector:
    app: 2048
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: 2048
  labels:
    app: 2048
    version: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 2048
      version: develop
  template:
    metadata:
      labels:
        app: 2048
        version: develop
    spec:
      containers:
      - name: 2048
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080
